### ISSUE TITLE
Reihenfolge der Radikale komplett willkürlich

### ISSUE THREAD

**Issue by slow-down** [AlexBocken/kanji#1]
Also ich weiß nicht ob es an der aktuellen Anki Version liegt oder nicht aber die Radikale werden mir in der komplett falschen Reihenfolge angezeigt. Ich habe z.B. in den ersten ~30 Karten sowas wie Pegasus gehabt ohne Truthahn oder Pferd gelernt zu haben. Ist das so gewollt oder was übersehe ich hier? Ich habe das Deck ganz normal über die Anki Seite runtergeladen und importiert ohne etwas zu verändern.

**Comment by AlexBocken** [comment]
Vielen Dank für die Meldung!
Ich erhalte das gleiche Resultat wenn ich von ankiweb importiere. Noch ist mir die Reihenfolge dabei  auch nicht ersichtlich, da es in der richtigen Reihenfolge die Karten importiert und in den Deckoptionen ist angegeben, dass die Zufügungsreihenfolge die Reihenfolge der neuen Karten bestimmen sollte.

Bis ich die korrekte Lösung finde kann ich ihnen einen Workaround anbieten, der manuell die Karten in die richtige Reihenfolge setzt.
Klicken sie im Hauptmenü auf `Browse` und wählen sie dort in der linken Leiste das Kanji Deck aus.
![image](https://user-images.githubusercontent.com/32177905/164159077-3d3dfbfc-da52-44af-94ee-7890f52e2b9e.png)

Wählen sie den Displaymodus `Notes` (grünes "N" an Stelle von blaues "C") und sortieren sie nach Note invertiert (Pfeil nach oben neben der Spalte `Note`)
![image](https://user-images.githubusercontent.com/32177905/164159363-0190294a-31ad-4bdc-bdf1-94203ad02c8e.png)

Wählen sie alle Karten aus mit `Ctrl+a`  und wählen sie das Reposition Menü via entweder `Ctrl+Shift+s` oder `Rechtsklick->Cards->Reposition`

![image](https://user-images.githubusercontent.com/32177905/164159615-56a5a6b4-e5a6-4efb-b9fb-7502f71644b7.png)

Standardeinstellungen akzeptieren und `OK` drücken. Die Karten sollten nun in richtiger Reihenfolge erscheinen.

Nochmals vielen Dank fürs melden!

**Comment by AlexBocken** [comment]
Ich habe soeben eine neue Version des Decks auf ankiweb geshared (es hat auch ein paar kleinere sonstigen Updates). Diese scheinte für mich zu funktionieren mit Anki 2.1.49 und 2.1.50. Könnten Sie mir wenn möglich bestätigen dass es auch für Sie klappt?

**Comment by slow-down** [comment]
ja jetzt ist alles in der korrekten reihenfolge. danke
